on:
  pull_request:
  issue_comment:
jobs:
  gitsensei_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request
    steps:
      - name: Git Sensei
        id: gitsensei
        uses: shivendrasoni/git-sensei-action@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}